#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# PATH {{{

# add ~/.local/bin
if [ -d "$HOME/.local/bin" ]; then
    PATH="$PATH:$HOME/.local/bin"
fi

# add my scripts
if [ -d "$HOME/code/scripts" ]; then
    PATH="$PATH:$HOME/code/scripts"
fi

export PATH

# }}}

# BASH SETTINGS {{{

# use a fancy prompt if possible
[ -f ~/dotfiles/shell/prompt.bash ] && . ~/dotfiles/shell/prompt.bash

set -o vi                                # use vi mode
export HISTSIZE=                         # unlimited history
export HISTFILESIZE=                     # unlimited history file
export HISTCONTROL=erasedups:ignorespace # no dups or entries starting w/space
export HISTTIMEFORMAT='%Y %b %d %T  '    # save timestamp with history entries

if shopt | grep -q '^histappend'; then
    shopt -s histappend                 # append to history when writing it
fi

if shopt | grep -q '^checkjobs'; then
    shopt -s checkjobs                  # warn if jobs running/stopped on exit
fi

# }}}

# ALIASES {{{

alias ls='ls -h --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias hw='todo list school'

# }}}

# FZF {{{

# source keybindings and completion scripts
[[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]] && \
    . /usr/share/doc/fzf/examples/key-bindings.bash
[[ -f /usr/share/doc/fzf/examples/completion.bash ]] && \
    . /usr/share/doc/fzf/examples/completion.bash

# use ripgrep by default
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'

# use ctrl-f as alternate to normal fzf ctrl-t since I use ctrl-t for tmux
bind -x '"\C-f": fzf-file-widget'

# }}}

# MISC {{{

export EDITOR=vim   # use vim as preferred editor
export RIPGREP_CONFIG_PATH="$HOME/dotfiles/ripgreprc" # set ripgrep config file

# disable flow control when in vim to map ctrl-s and ctrl-q
[[ -f ~/dotfiles/vim/no-flow-control.bash ]] && \
    . ~/dotfiles/vim/no-flow-control.bash

# enable tab completion for common commands - requires bash-completion package
[[ -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

# source bashmarks
[[ -f ~/dotfiles/shell/bashmarks.sh ]] && . ~/dotfiles/shell/bashmarks.sh

# source an extra file that isn't tracked by dotfiles repo for local-only configs
[[ -f ~/.bash_extra ]] && . ~/.bash_extra

# start sway on login
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    command -v sway &> /dev/null && exec sway
fi

# start tmux by default - needs to be last for settings set here to apply to
# tmux server
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
   tmux attach -t default || tmux new -s default
fi

# }}}

# vim:foldmethod=marker:foldlevel=0
