#!/bin/bash

# Run `vdirsyncer sync` periodically, sending output to a log.

LOG_FILE="$1"
if [ -z "$LOG_FILE" ]; then
    LOG_FILE="$HOME/.config/vdirsyncer/vdir_autosync.log"   # default log file
fi

while true; do
    date >> "$LOG_FILE"                 # print datetime to log
    vdirsyncer sync &>> "$LOG_FILE"     # sync and send stdout/stderr to log
    echo >> "$LOG_FILE"                 # print new line to log
    sleep 600                           # 10 minutes
done

